__Vi bygger om logiken för att plocka ut 24 hästar. Optimerad modell__

In [17]:
# Common imports
import numpy as np
import os
import pandas as pd


# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

In [18]:
# Necessary Sklearn objects used in the analysis
from sklearn.metrics import roc_curve, auc
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn import preprocessing

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Imputer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import FeatureUnion

In [19]:
from DataPipeline import DataFrameSelector
from sklearn.externals import joblib

__Läser in filen som ska köras__

In [20]:
df1 = pd.read_excel('RealDataV75TillUffeU20190413.xlsx')

In [21]:
df1 = df1.sort_values(['Lopp','Hast'], ascending = ['True','False']).reset_index()

In [22]:
# Importera model som ska användas
rf = joblib.load('Travmodel_v5.pkl')

In [23]:
# Import av datapipeline som ska användas
full_pipeline = joblib.load('Pipeline_v5.pkl')

__Definierar de variabler som ska användas i datasetet__

In [24]:

# Numerisk variabel 

num_attribs = ['VLP',
 'SVLP',
 'VSVLP',
 'VPN_SUM',
 'VPN_SUM_ORD',
 'VPK_SUM',
 'VPK_SUM_ORD',
 'VLPB',
 'SVLPB',
 'VSVLPB',
 'E_P',
 'E_P_Num',
 'E_N',
 'E_R',
 'E_U',
 'G_R',
 'A_R',
 'T_R',
 'ToR',
 'Ts_R']

__Kör modellen och plockar fram de 24 hästarna med högst score__

In [25]:
df1['GRUPP'] = df1.GRUPP.astype('object')
features = full_pipeline.fit_transform(df1)

predict = rf.predict_proba(features)

predict_cutoff = pd.DataFrame({'Prob0':predict[:,0],'Prob1':predict[:,1]}).sort_values('Prob1', ascending = False).iloc[40]['Prob1']

y_pred = np.where( predict[:,1] > predict_cutoff,1,0)

In [26]:
# Gör om scorad array till en lista - multidimensionell
stack = predict.tolist()

In [27]:
# Sedan plockar vi den scorade sannolikheten att vara vinnare - 1
# Transformerar denna sannolikhet till en dataframe
last = []
for x in stack:
    last.append(x[1])
scored = {'Score':last}
# Konverterar till Dataframe
df_scored = pd.DataFrame.from_dict(scored)

In [28]:
# Gör om till lista och stoppar in i ett dictionary
pred = y_pred.tolist()
prediction = {'Predict':pred}
# Konverterar till Dataframe
df_pred = pd.DataFrame.from_dict(prediction)

In [29]:
df_predict1 = df1.merge(df_pred, right_index = True, left_index = True)
df_predict2 = df_predict1.merge(df_scored,  right_index = True, left_index = True)

In [30]:
df1_out = df_predict2[df_predict2.Predict == 1][['Lopp','Hast','Score']]. \
sort_values(['Lopp','Score'], ascending = [True,False])
df1_out

    Lopp  Hast     Score
4      1     5  0.444878
2      1     3  0.208166
7      1     9  0.138289
6      1     8  0.058119
1      1     2  0.054970
8      2     2  0.175793
16     2    10  0.134430
9      2     3  0.114984
18     2    12  0.107679
11     2     5  0.052412
23     3     5  0.816433
20     3     2  0.227561
19     3     1  0.080454
24     3     6  0.070644
25     3     7  0.060617
36     4     9  0.183188
39     4    12  0.166923
34     4     7  0.129890
37     4    10  0.077282
40     5     1  0.197050
48     5     9  0.120362
50     5    11  0.116011
44     5     5  0.102484
47     5     8  0.065253
43     5     4  0.060254
45     5     6  0.053374
55     6     4  0.179630
53     6     2  0.165874
60     6     9  0.158263
56     6     5  0.100589
57     6     6  0.080892
54     6     3  0.064691
52     6     1  0.051964
66     7     3  0.227676
67     7     4  0.119691
71     7     8  0.116466
65     7     2  0.105357
74     7    11  0.091931
68     7     5  0.071741
72     7     9  0.065233

In [31]:
len(df1_out)

40

__Export till excel__

In [32]:
df1_out.to_excel('Outtake20190413_v3.xlsx', index = False)